### PR TITLE
Added showall parameter 

### PR DESCRIPTION
**Pull request by thofstrand**
Added `showall` parameter to JLDetectChangePoint that shows all candidate graphs. Also made space to find best plot, which I need to figure out how to do. Also need to make it print the graphs prettier.

### CODE REVIEW

**Comment by speegled** [comment]
This is a very good start! I was hoping to have a single plot which had the 5 scatterplots with geom_smooth plus the best probvec (you can use BFIC and pick the one that has the largest $value), appropriately labeled.

**Comment by thofstrand** [comment]
> This is a very good start! I was hoping to have a single plot which had the 5 scatterplots with geom_smooth plus the best probvec (you can use BFIC and pick the one that has the largest $value), appropriately labeled.

I am not sure how to plot them all at once since they are each plotted separately within the detectchangepoint() function. I agree they should be together and I will try to figure out how to merge them into one plot, hopefully.

**Comment by speegled** [comment]
How about if for now, you pick the one with highest BFIC and plot that one?

**Comment by speegled** [comment]
Did you compare the two plots? It seems hard for me to tell which is working better in general.

**Comment by speegled** [comment]
OK, I modified the code to plot both the BFIC one and the range of values one, and the BFIC one is definitely working better on the Lennon example. I think the reason in this case is because the best BFIC one isn't the only one that has the smallest possible range of values. The other algorithm picks the first (random) dimension which has the minimum possible range of values, which isn't necessarily the best.

**Comment by thofstrand** [comment]
Okay awesome I will just utilize that then over the range method. Did you push this code to git? I would love to take a look to continue working on it!

**Comment by speegled** [comment]
I merged your pull request and made one silly change that you should pull before continuing to work on it. Everything on master is up-to-date and is consistent with what I have locally. It would be nice to use the BFIC method working in both the setdetail = T case as well as the setdetail = F case.

________________________________________
Van: thofstrand ***@***.***>
Gestuur: Vrydag 24 Junie 2022 01:51
aan: speegled/cpbaywave
Aa: Darrin Speegle; State change
onderwerp: [External] Re: [speegled/cpbaywave] Added showall parameter  (PR #8)

Okay awesome I will just utilize that then over the range method. Did you push this code to git? I would love to take a look to continue working on it!

**Pull request merged**
